-- =====================================================================
-- Lookup vocabularies: grading scale, defects, cleaning methods
-- These ship as defaults and stay editable from the app.
-- =====================================================================

INSERT INTO condition_grades (code, label, score, description, sort_order) VALUES
  ('M',   'Mint',            100, 'As it left the factory. Unplayed or near enough; full gloss, no marks, crisp starting groove.', 1),
  ('NM',  'Near Mint',        92, 'Played with care a handful of times. No visible damage at arm''s length, surface still bright.', 2),
  ('EX+', 'Excellent Plus',   85, 'Light play. A few faint marks visible only under raking light; plays with almost no added noise.', 3),
  ('EX',  'Excellent',        78, 'Clearly played but well kept. Minor scuffing, no cracks or chips, plays cleanly throughout.', 4),
  ('VG+', 'Very Good Plus',   70, 'Honest wear. Visible scuffing and light groove wear; some surface noise but the performance is unhindered.', 5),
  ('VG',  'Very Good',        62, 'Well played. Noticeable noise, possibly a small edge chip clear of the grooves; plays end to end.', 6),
  ('G+',  'Good Plus',        52, 'Heavy wear or a repaired fault. Plays through with significant noise; passages may be dulled.', 7),
  ('G',   'Good',             45, 'Rough. Groove wear throughout, possible chip or hairline crack; plays but the noise intrudes.', 8),
  ('F',   'Fair',             30, 'Damaged. Cracks, chips or mould scarring; plays only in part, or with repeats and jumps.', 9),
  ('P',   'Poor',             15, 'Badly damaged. Barely playable; kept for the title rather than the sound.', 10),
  ('UNP', 'Unplayable',        5, 'Broken, split, badly warped or grown over. Held as a filler or for parts.', 11),
  ('UNG', 'Ungraded',          0, 'Not yet examined or graded.', 12);

-- Defects, with the collector-facing advice each one carries.
INSERT INTO defect_types (code, label, category, description, care_advice, is_terminal, sort_order) VALUES
  ('crack',        'Crack',                'structural',
   'A fracture running through the record wall, often from the rim inward.',
   'Do not play until stabilised: the stylus will widen the crack every revolution. Store flat-shelved, away from temperature swings.', false, 1),
  ('chip',         'Chip',                 'structural',
   'A piece missing from an edge. Harmless clear of the grooves; a skip if not.',
   'Note whether the chip reaches the grooved area. If it does, expect a repeating jump at that point.', false, 2),
  ('broken',       'Broken / in pieces',   'structural',
   'The cylinder has come apart.',
   'Nothing to be done for playback. Keep the pieces together and boxed; the label and title band are still documentary evidence.', true, 3),
  ('celluloid_split', 'Celluloid split',   'structural',
   'The celluloid tube has split along its length, usually because it shrank around a core that did not.',
   'Progressive and effectively terminal. Keep cool and stable; heat accelerates the shrinkage that causes it.', true, 4),
  ('warped',       'Warped / out of round','structural',
   'The cylinder is no longer truly circular, so the stylus rises and falls once per turn.',
   'Heard as a slow wow on playback. Usually caused by heat or by long storage on a deformed core. Do not attempt to reshape.', false, 5),
  ('shrunken',     'Shrunken onto core',   'core',
   'Celluloid contracted tightly onto the plaster core, putting the tube under permanent tension.',
   'Precedes splitting. Store cool and at steady humidity; never leave in a car, attic or sunlit room.', false, 6),
  ('core_crack',   'Core cracked',         'core',
   'The plaster of Paris core has fractured.',
   'May let the cylinder sit unevenly on the mandrel. Handle by the ends only and support the full length when lifting.', false, 7),
  ('core_crumbling','Core crumbling',      'core',
   'The plaster core is powdering away, often from damp.',
   'Dry storage is essential. Powder shed inside the box will find its way into the grooves.', false, 8),
  ('core_separation','Core separation',    'core',
   'The celluloid has parted company with its core.',
   'The tube may spin freely or sit loose on the mandrel. Do not play; the record can be flung off at speed.', false, 9),
  ('mould',        'Mould / fungus',       'contamination',
   'Fungal growth feeding on the record surface, most often on wax cylinders stored damp.',
   'Isolate from the rest of the collection at once — it spreads. Wax must never be washed; brush dry and lower the storage humidity.', false, 10),
  ('bloom',        'Bloom / white haze',   'surface',
   'A whitish film of migrated fatty acids on the surface of a wax cylinder.',
   'Normal in old wax and not itself decay. Brush very gently when dry; solvents will take the surface with the bloom.', false, 11),
  ('grime',        'Dirt / grime',         'contamination',
   'Accumulated dust and household soil in the grooves.',
   'The most common cause of noise, and the most reversible. Celluloid tolerates a gentle distilled-water clean; wax does not.', false, 12),
  ('groove_wear',  'Groove wear',          'surface',
   'The groove walls are worn from repeated playing, especially with a worn or wrong stylus.',
   'Irreversible. Play with a correctly profiled reproducer and check the stylus before every session.', false, 13),
  ('scratch',      'Scratch / gouge',      'surface',
   'A mark cut across the grooves.',
   'Heard as a tick once per revolution, or a jump if deep. Nothing can be done, but note its position for reference.', false, 14),
  ('stylus_damage','Stylus damage',        'surface',
   'A skidding or dropped stylus has ploughed across the surface.',
   'Lower the reproducer with the carriage, never by hand, and never onto a spinning cylinder.', false, 15),
  ('water_stain',  'Water damage',         'contamination',
   'Staining or swelling from having been wet.',
   'Check the core first: plaster that has been soaked rarely recovers its shape.', false, 16),
  ('insect',       'Insect damage',        'contamination',
   'Grazing marks left by insects on a wax surface.',
   'Inspect the whole box and any neighbouring cylinders; the culprits may still be present.', false, 17),
  ('adhesive',     'Adhesive residue',     'contamination',
   'Tape, glue or label residue on the record or box.',
   'Never peel tape from a record surface. Leave it and note it rather than risk taking the surface with it.', false, 18),
  ('noise_heavy',  'Heavy surface noise',  'audio',
   'A loud hiss or roar under the music.',
   'Try a careful clean first if the material allows; a great deal of "wear" turns out to be dirt.', false, 19),
  ('ticks',        'Ticks / pops',         'audio',
   'Regular or irregular impulses over the recording.',
   'Regular ticks are physical marks; irregular ones are usually debris in the groove.', false, 20),
  ('skip',         'Skip / repeat',        'audio',
   'The stylus jumps a thread or locks in one groove.',
   'Nearly always a crack, chip or gouge crossing the grooves. Find the mark before playing again.', false, 21),
  ('muffled',      'Muffled / dull',       'audio',
   'The recording sounds soft and lacking in top.',
   'Can be wear, can be a shallow original recording, can be the reproducer. Compare against another copy before blaming the record.', false, 22),
  ('label_damage', 'Title band damaged',   'packaging',
   'The paper title band or end label is torn, faded or missing.',
   'Photograph what survives. A cylinder without its band can still be identified from the moulded end title.', false, 23),
  ('box_damage',   'Box damaged',          'packaging',
   'The carton is crushed, split, or its lid is missing.',
   'Worth keeping even in poor condition: the box carries the title, number and often a dealer''s mark.', false, 24),
  ('box_missing',  'Box missing',          'packaging',
   'The cylinder has no original container.',
   'Store in a modern archival tube rather than loose. Loose cylinders chip.', false, 25),
  ('box_mildew',   'Box mildew',           'packaging',
   'Mould in the carton, felt or lid.',
   'Separate the record from the box until the box is dry and clean, or the record will be re-infected.', false, 26);

-- Cleaning methods. safe_for is what drives the warning shown when a method
-- is logged against a material it should not be used on — the wax/celluloid
-- distinction is the one that ruins records.
INSERT INTO cleaning_methods (code, label, description, safe_for, is_risky, sort_order) VALUES
  ('none', 'Not cleaned — as found',
   'Recorded as received, with no treatment.',
   '{brown_wax,black_wax,metallic_soap,celluloid,condensite,unknown}', false, 1),
  ('dry_brush', 'Soft dry brush',
   'A clean, soft brush worked along the grooves while the cylinder turns slowly. The only treatment wax should normally receive.',
   '{brown_wax,black_wax,metallic_soap,celluloid,condensite,unknown}', false, 2),
  ('air', 'Compressed / bulb air',
   'Loose dust blown out of the grooves. Use gentle pressure and never a can held at an angle.',
   '{brown_wax,black_wax,metallic_soap,celluloid,condensite,unknown}', false, 3),
  ('vacuum_brush', 'Vacuum with soft brush',
   'Low-suction vacuum through a soft brush head, lifting debris rather than pushing it deeper.',
   '{brown_wax,black_wax,metallic_soap,celluloid,condensite,unknown}', false, 4),
  ('dry_cloth', 'Dry microfibre wipe',
   'A lint-free cloth drawn lengthwise along the grooves, never across them.',
   '{celluloid,condensite,unknown}', false, 5),
  ('distilled_water', 'Distilled water, damp swab',
   'A barely damp swab of distilled water on the celluloid surface, dried at once. The core must stay dry.',
   '{celluloid,condensite}', false, 6),
  ('mild_detergent', 'Distilled water with mild detergent',
   'A trace of non-ionic detergent in distilled water, applied to celluloid and rinsed with plain distilled water.',
   '{celluloid}', false, 7),
  ('photoflo', 'Wetting-agent solution',
   'A conservation-grade wetting agent in distilled water, used to lift grime from celluloid grooves.',
   '{celluloid}', false, 8),
  ('ultrasonic', 'Ultrasonic bath',
   'Immersion cleaning. Effective on bare celluloid but hazardous: the plaster core cannot be allowed to soak.',
   '{celluloid}', true, 9),
  ('isopropyl', 'Dilute isopropyl alcohol',
   'A dilute alcohol wipe. Attacks wax and can haze celluloid — kept here because it is commonly reported, not because it is advised.',
   '{}', true, 10),
  ('solvent', 'Solvent / naphtha',
   'Petroleum solvent on a swab. High risk of surface damage on any cylinder material.',
   '{}', true, 11),
  ('fungicide', 'Fungicidal treatment',
   'Targeted anti-fungal treatment of a mould-affected record.',
   '{celluloid}', true, 12),
  ('professional', 'Professional conservation',
   'Cleaned or stabilised by a conservator or archive.',
   '{brown_wax,black_wax,metallic_soap,celluloid,condensite,unknown}', false, 13),
  ('other', 'Other method',
   'Anything not listed; describe it in the notes.',
   '{brown_wax,black_wax,metallic_soap,celluloid,condensite,unknown}', false, 14);

-- The collector's own shelf, created so the app has somewhere to put things
-- on first run.
INSERT INTO collections (slug, name, owner_name, description, is_default) VALUES
  ('my-amberola', 'My Amberola', NULL,
   'Four-minute cylinders held for the Edison Amberola.', true);
